version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"  # Expose Flask's port
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app  # Mount the current directory to the container (for development)
    depends_on:
      - db  # Ensure the database service is up before Flask starts

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: fruitdb
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres-data:
    driver: local
